Updated file

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -5,19 +5,20 @@ if [ "$#" -eq 0 ]; then
 	exit 1
 fi
 
-MYSQL_PWD="$1"
-MYSQL_USER="root"
 BACKUP_FILE="backup.sql"
 
-# Run MySQL dump command
-mysqldump -u "$MYSQL_USER" -p"$MYSQL_PWD" --all-databases > "$BACKUP_FILE"
-
-# Check if mysqldump succeeded
-if ! mycmd; then
+# Run mysqldump command
+if ! mysqldump -uroot -p"$1" --all-databases > "$BACKUP_FILE"; then 
 	echo "mysqldump failed"
 	exit 1
 fi
 
 # Create archive of backup
-FORMATTED_DATE=$(date +%d-%m-%Y)
-tar -czvf "$FORMATTED_DATE".tar.gz "$BACKUP_FILE"
+DATE=$(date +%d-%m-%Y)
+tar -czf "$DATE.tar.gz" "$BACKUP_FILE"
+if ! tar -czf "$DATE.tar.gz" "$BACKUP_FILE"; then
+	echo "Archive creation failed"
+	exit 1
+fi
+
+echo "Archive created succesfully"
